call cppapi#function('EVT_WDFDEVICE_WDM_IRP_PREPROCESS(', 'WDFDEVICE inDevice, PIRP ioIrp)', 'NTSTATUS', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_CLEANUP(', 'WDFCHILDLIST inChildList, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER ioAddressDescription)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_COPY(', 'WDFCHILDLIST inChildList, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER inSourceAddressDescription, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER outDestinationAddressDescription)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_ADDRESS_DESCRIPTION_DUPLICATE(', 'WDFCHILDLIST inChildList, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER inSourceAddressDescription, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER outDestinationAddressDescription)', 'NTSTATUS', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_CREATE_DEVICE(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inIdentificationDescription, PWDFDEVICE_INIT inChildInit)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_DEVICE_REENUMERATED(', 'WDFCHILDLIST inChildList, WDFDEVICE inOldDevice, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER inOldAddressDescription, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER outNewAddressDescription)', 'BOOLEAN', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_CLEANUP(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER outIdentificationDescription)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COMPARE(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inFirstIdentificationDescription, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inSecondIdentificationDescription)', 'BOOLEAN', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_COPY(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inSourceIdentificationDescription, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER outDestinationIdentificationDescription)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_IDENTIFICATION_DESCRIPTION_DUPLICATE(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inSourceIdentificationDescription, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER outDestinationIdentificationDescription)', 'NTSTATUS', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_CHILD_LIST_SCAN_FOR_CHILDREN(', 'WDFCHILDLIST inChildList)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_ARM_WAKE_FROM_S0(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_ARM_WAKE_FROM_SX(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_ARM_WAKE_FROM_SX_WITH_REASON(', 'WDFDEVICE inDevice, BOOLEAN inDeviceWakeEnabled, BOOLEAN inChildrenArmedForWake)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_D0_ENTRY(', 'WDFDEVICE inDevice, WDF_POWER_DEVICE_STATE inPreviousState)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_D0_ENTRY_POST_INTERRUPTS_ENABLED(', 'WDFDEVICE inDevice, WDF_POWER_DEVICE_STATE inPreviousState)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_D0_EXIT(', 'WDFDEVICE inDevice, WDF_POWER_DEVICE_STATE inTargetState)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_D0_EXIT_PRE_INTERRUPTS_DISABLED(', 'WDFDEVICE inDevice, WDF_POWER_DEVICE_STATE inTargetState)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_DISABLE_WAKE_AT_BUS(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_DISARM_WAKE_FROM_S0(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_DISARM_WAKE_FROM_SX(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_EJECT(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_ENABLE_WAKE_AT_BUS(', 'WDFDEVICE inDevice, SYSTEM_POWER_STATE inPowerState)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_FILE_CREATE(', 'WDFDEVICE inDevice, WDFREQUEST inRequest, WDFFILEOBJECT inFileObject)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS(', 'WDFDEVICE inDevice, WDFIORESREQLIST inIoResourceRequirementsList)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION(', 'WDFDEVICE inDevice, PCWDF_DEVICE_PNP_NOTIFICATION_DATA inNotificationData)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION(', 'WDFDEVICE inDevice, PCWDF_DEVICE_POWER_POLICY_NOTIFICATION_DATA inNotificationData)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION(', 'WDFDEVICE inDevice, PCWDF_DEVICE_POWER_NOTIFICATION_DATA inNotificationData)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_PREPARE_HARDWARE(', 'WDFDEVICE inDevice, WDFCMRESLIST inResourcesRaw, WDFCMRESLIST inResourcesTranslated)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_PROCESS_QUERY_INTERFACE_REQUEST(', 'WDFDEVICE inDevice, LPGUID inInterfaceType, PINTERFACE ioExposedInterface, PVOID ioExposedInterfaceSpecificData)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_QUERY_REMOVE(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_QUERY_STOP(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_RELATIONS_QUERY(', 'WDFDEVICE inDevice, DEVICE_RELATION_TYPE inRelationType)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_RELEASE_HARDWARE(', 'WDFDEVICE inDevice, WDFCMRESLIST inResourcesTranslated)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_REMOVE_ADDED_RESOURCES(', 'WDFDEVICE inDevice, WDFCMRESLIST inResourcesRaw, WDFCMRESLIST inResourcesTranslated)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_RESOURCES_QUERY(', 'WDFDEVICE inDevice, WDFCMRESLIST inResources)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_RESOURCE_REQUIREMENTS_QUERY(', 'WDFDEVICE inDevice, WDFIORESREQLIST inIoResourceRequirementsList)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SELF_MANAGED_IO_CLEANUP(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SELF_MANAGED_IO_FLUSH(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SELF_MANAGED_IO_INIT(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SELF_MANAGED_IO_RESTART(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SELF_MANAGED_IO_SUSPEND(', 'WDFDEVICE inDevice)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SET_LOCK(', 'WDFDEVICE inDevice, BOOLEAN inIsLocked)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SHUTDOWN_NOTIFICATION(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_SURPRISE_REMOVAL(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_USAGE_NOTIFICATION(', 'WDFDEVICE inDevice, WDF_SPECIAL_FILE_TYPE inNotificationType, BOOLEAN inIsInNotificationPath)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_WAKE_FROM_S0_TRIGGERED(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DEVICE_WAKE_FROM_SX_TRIGGERED(', 'WDFDEVICE inDevice)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DMA_ENABLER_DISABLE(', 'WDFDMAENABLER inDmaEnabler)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DMA_ENABLER_ENABLE(', 'WDFDMAENABLER inDmaEnabler)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DMA_ENABLER_FLUSH(', 'WDFDMAENABLER inDmaEnabler)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_START(', 'WDFDMAENABLER inDmaEnabler)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DMA_ENABLER_SELFMANAGED_IO_STOP(', 'WDFDMAENABLER inDmaEnabler)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DRIVER_DEVICE_ADD(', 'WDFDRIVER inDriver, PWDFDEVICE_INIT ioDeviceInit)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_DRIVER_UNLOAD(', 'WDFDRIVER inDriver)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_FILE_CLEANUP(', 'WDFFILEOBJECT inFileObject)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_FILE_CLOSE(', 'WDFFILEOBJECT inFileObject)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_IO_ALLOCATE_REQUEST_RESOURCES(', 'WDFQUEUE inQueue, WDFREQUEST inRequest)', 'NTSTATUS', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_ALLOCATE_RESOURCES_FOR_RESERVED_REQUEST(', 'WDFQUEUE inQueue, WDFREQUEST inRequest)', 'NTSTATUS', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE(', 'WDFQUEUE inQueue, WDFREQUEST inRequest)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_DEFAULT(', 'WDFQUEUE inQueue, WDFREQUEST inRequest)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL(', 'WDFQUEUE inQueue, WDFREQUEST inRequest, size_t inOutputBufferLength, size_t inInputBufferLength, ULONG inIoControlCode)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_INTERNAL_DEVICE_CONTROL(', 'WDFQUEUE inQueue, WDFREQUEST inRequest, size_t inOutputBufferLength, size_t inInputBufferLength, ULONG inIoControlCode)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_READ(', 'WDFQUEUE inQueue, WDFREQUEST inRequest, size_t inLength)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_RESUME(', 'WDFQUEUE inQueue, WDFREQUEST inRequest)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_STOP(', 'WDFQUEUE inQueue, WDFREQUEST inRequest, ULONG inActionFlags)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_IO_WRITE(', 'WDFQUEUE inQueue, WDFREQUEST inRequest, size_t inLength)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_QUEUE_STATE(', 'WDFQUEUE inQueue, WDFCONTEXT inContext)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_IO_TARGET_QUERY_REMOVE(', 'WDFIOTARGET inIoTarget)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_IO_TARGET_REMOVE_CANCELED(', 'WDFIOTARGET inIoTarget)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_IO_TARGET_REMOVE_COMPLETE(', 'WDFIOTARGET inIoTarget)', 'VOID', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_IO_WDM_IRP_FOR_FORWARD_PROGRESS(', 'WDFQUEUE inQueue, PIRP inIrp)', 'WDF_IO_FORWARD_PROGRESS_ACTION', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_OBJECT_CONTEXT_CLEANUP(', 'WDFOBJECT inObject)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_OBJECT_CONTEXT_DESTROY(', 'WDFOBJECT inObject)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_USB_READERS_FAILED(', 'WDFUSBPIPE inPipe, NTSTATUS inStatus, USBD_STATUS inUsbdStatus)', 'BOOLEAN', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_USB_READER_COMPLETION_ROUTINE(', 'WDFUSBPIPE inPipe, WDFMEMORY inBuffer, size_t inNumBytesTransferred, WDFCONTEXT inContext)', 'VOID', '#DISPATCH_LEVEL')
call cppapi#function('EVT_WDF_WMI_INSTANCE_EXECUTE_METHOD(', 'WDFWMIINSTANCE inWmiInstance, ULONG inMethodId, ULONG inInBufferSize, ULONG inOutBufferSize, PVOID Buffer, PULONG outBufferUsed)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_WMI_INSTANCE_QUERY_INSTANCE(', 'WDFWMIINSTANCE inWmiInstance, ULONG inOutBufferSize, PVOID OutBuffer, PULONG outBufferUsed)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_WMI_INSTANCE_SET_INSTANCE(', 'WDFWMIINSTANCE inWmiInstance, ULONG inInBufferSize, PVOID InBuffer)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_WMI_INSTANCE_SET_ITEM(', 'WDFWMIINSTANCE inWmiInstance, ULONG inDataItemId, ULONG inInBufferSize, PVOID InBuffer)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('EVT_WDF_WMI_PROVIDER_FUNCTION_CONTROL(', 'WDFWMIPROVIDER inWmiProvider, WDF_WMI_PROVIDER_CONTROL inControl, BOOLEAN inEnable)', 'NTSTATUS', '#PASSIVE_LEVEL')
call cppapi#function('WdfChildListAddOrUpdateChildDescriptionAsPresent(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inIdentificationDescription, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER inAddressDescription)', 'NTSTATUS', '')
call cppapi#function('WdfChildListBeginIteration(', 'WDFCHILDLIST inChildList, PWDF_CHILD_LIST_ITERATOR inIterator)', 'VOID', '')
call cppapi#function('WdfChildListBeginScan(', 'WDFCHILDLIST inChildList)', 'VOID', '')
call cppapi#function('WdfChildListCreate(', 'WDFDEVICE inDevice, PWDF_CHILD_LIST_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inChildListAttributes, outWDFCHILDLIST* ChildList)', 'NTSTATUS', '')
call cppapi#function('WdfChildListEndIteration(', 'WDFCHILDLIST inChildList, PWDF_CHILD_LIST_ITERATOR inIterator)', 'VOID', '')
call cppapi#function('WdfChildListEndScan(', 'WDFCHILDLIST inChildList)', 'VOID', '')
call cppapi#function('WdfChildListGetDevice(', 'WDFCHILDLIST inChildList)', 'WDFDEVICE', '')
call cppapi#function('WdfChildListRequestChildEject(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inIdentificationDescription)', 'BOOLEAN', '')
call cppapi#function('WdfChildListRetrieveAddressDescription(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inIdentificationDescription, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER ioAddressDescription)', 'NTSTATUS', '')
call cppapi#function('WdfChildListRetrieveNextDevice(', 'WDFCHILDLIST inChildList, PWDF_CHILD_LIST_ITERATOR inIterator, outWDFDEVICE* Device, PWDF_CHILD_RETRIEVE_INFO ioInfo)', 'NTSTATUS', '')
call cppapi#function('WdfChildListRetrievePdo(', 'WDFCHILDLIST inChildList, PWDF_CHILD_RETRIEVE_INFO ioRetrieveInfo)', 'WDFDEVICE', '')
call cppapi#function('WdfChildListUpdateAllChildDescriptionsAsPresent(', 'WDFCHILDLIST inChildList)', 'VOID', '')
call cppapi#function('WdfChildListUpdateChildDescriptionAsMissing(', 'WDFCHILDLIST inChildList, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER inIdentificationDescription)', 'NTSTATUS', '')
call cppapi#function('WdfCmResourceListAppendDescriptor(', 'WDFCMRESLIST inList, PCM_PARTIAL_RESOURCE_DESCRIPTOR inDescriptor)', 'NTSTATUS', '')
call cppapi#function('WdfCmResourceListGetCount(', 'WDFCMRESLIST inList)', 'ULONG', '')
call cppapi#function('WdfCmResourceListGetDescriptor(', 'WDFCMRESLIST inList, ULONG inIndex)', 'PCM_PARTIAL_RESOURCE_DESCRIPTOR', '')
call cppapi#function('WdfCmResourceListInsertDescriptor(', 'WDFCMRESLIST inList, PCM_PARTIAL_RESOURCE_DESCRIPTOR inDescriptor, ULONG inIndex)', 'NTSTATUS', '')
call cppapi#function('WdfCmResourceListRemove(', 'WDFCMRESLIST inList, ULONG inIndex)', 'VOID', '')
call cppapi#function('WdfCmResourceListRemoveByDescriptor(', 'WDFCMRESLIST inList, PCM_PARTIAL_RESOURCE_DESCRIPTOR inDescriptor)', 'VOID', '')
call cppapi#function('WdfCollectionAdd(', 'WDFCOLLECTION inCollection, WDFOBJECT inObject)', 'NTSTATUS', '')
call cppapi#function('WdfCollectionCreate(', 'PWDF_OBJECT_ATTRIBUTES inCollectionAttributes, outWDFCOLLECTION* Collection)', 'NTSTATUS', '')
call cppapi#function('WdfCollectionGetCount(', 'WDFCOLLECTION inCollection)', 'ULONG', '')
call cppapi#function('WdfCollectionGetFirstItem(', 'WDFCOLLECTION inCollection)', 'WDFOBJECT', '')
call cppapi#function('WdfCollectionGetItem(', 'WDFCOLLECTION inCollection, ULONG inIndex)', 'WDFOBJECT', '')
call cppapi#function('WdfCollectionGetLastItem(', 'WDFCOLLECTION inCollection)', 'WDFOBJECT', '')
call cppapi#function('WdfCollectionRemove(', 'WDFCOLLECTION inCollection, WDFOBJECT inItem)', 'VOID', '')
call cppapi#function('WdfCollectionRemoveItem(', 'WDFCOLLECTION inCollection, ULONG inIndex)', 'VOID', '')
call cppapi#function('WdfCommonBufferCreate(', 'WDFDMAENABLER inDmaEnabler, size_t inLength, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFCOMMONBUFFER* CommonBuffer)', 'NTSTATUS', '')
call cppapi#function('WdfCommonBufferCreateWithConfig(', 'WDFDMAENABLER inDmaEnabler, size_t inLength, PWDF_COMMON_BUFFER_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFCOMMONBUFFER* CommonBuffer)', 'NTSTATUS', '')
call cppapi#function('WdfCommonBufferGetAlignedLogicalAddress(', 'WDFCOMMONBUFFER inCommonBuffer)', 'PHYSICAL_ADDRESS', '')
call cppapi#function('WdfCommonBufferGetAlignedVirtualAddress(', 'WDFCOMMONBUFFER inCommonBuffer)', 'PVOID', '')
call cppapi#function('WdfCommonBufferGetLength(', 'WDFCOMMONBUFFER inCommonBuffer)', 'size_t', '')
call cppapi#function('WdfControlDeviceInitAllocate(', 'WDFDRIVER inDriver, CONST inUNICODE_STRING* SDDLString)', 'PWDFDEVICE_INIT', '')
call cppapi#function('WdfControlDeviceInitSetShutdownNotification(', 'PWDFDEVICE_INIT inDeviceInit, PFN_WDF_DEVICE_SHUTDOWN_NOTIFICATION inNotification, UCHAR inFlags)', 'VOID', '')
call cppapi#function('WdfControlFinishInitializing(', 'WDFDEVICE inDevice)', 'VOID', '')
call cppapi#function('WdfDeviceAddDependentUsageDeviceObject(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inDependentDevice)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAddQueryInterface(', 'WDFDEVICE inDevice, PWDF_QUERY_INTERFACE_CONFIG inInterfaceConfig)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAddRemovalRelationsPhysicalDevice(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inPhysicalDevice)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAllocAndQueryProperty(', 'WDFDEVICE inDevice, DEVICE_REGISTRY_PROPERTY inDeviceProperty, POOL_TYPE inPoolType, PWDF_OBJECT_ATTRIBUTES inPropertyMemoryAttributes, outWDFMEMORY* PropertyMemory)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAssignMofResourceName(', 'WDFDEVICE inDevice, PCUNICODE_STRING inMofResourceName)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAssignS0IdleSettings(', 'WDFDEVICE inDevice, PWDF_DEVICE_POWER_POLICY_IDLE_SETTINGS inSettings)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceAssignSxWakeSettings(', 'WDFDEVICE inDevice, PWDF_DEVICE_POWER_POLICY_WAKE_SETTINGS inSettings)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceClearRemovalRelationsDevices(', 'WDFDEVICE inDevice)', 'VOID', '')
call cppapi#function('WdfDeviceConfigureRequestDispatching(', 'WDFDEVICE inDevice, WDFQUEUE inQueue, WDF_REQUEST_TYPE inRequestType)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceCreate(', 'ioPWDFDEVICE_INIT* DeviceInit, PWDF_OBJECT_ATTRIBUTES inDeviceAttributes, outWDFDEVICE* Device)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceCreateDeviceInterface(', 'WDFDEVICE inDevice, CONST inGUID* InterfaceClassGUID, PCUNICODE_STRING inReferenceString)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceCreateSymbolicLink(', 'WDFDEVICE inDevice, PCUNICODE_STRING inSymbolicLinkName)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceEnqueueRequest(', 'WDFDEVICE inDevice, WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceGetAlignmentRequirement(', 'WDFDEVICE inDevice)', 'ULONG', '')
call cppapi#function('WdfDeviceGetCharacteristics(', 'WDFDEVICE inDevice)', 'ULONG', '')
call cppapi#function('WdfDeviceGetDefaultQueue(', 'WDFDEVICE inDevice)', 'WDFQUEUE', '')
call cppapi#function('WdfDeviceGetDevicePnpState(', 'WDFDEVICE inDevice)', 'WDF_DEVICE_PNP_STATE', '')
call cppapi#function('WdfDeviceGetDevicePowerPolicyState(', 'WDFDEVICE inDevice)', 'WDF_DEVICE_POWER_POLICY_STATE', '')
call cppapi#function('WdfDeviceGetDevicePowerState(', 'WDFDEVICE inDevice)', 'WDF_DEVICE_POWER_STATE', '')
call cppapi#function('WdfDeviceGetDeviceState(', 'WDFDEVICE inDevice, PWDF_DEVICE_STATE outDeviceState)', 'VOID', '')
call cppapi#function('WdfDeviceGetDriver(', 'WDFDEVICE inDevice)', 'WDFDRIVER', '')
call cppapi#function('WdfDeviceGetFileObject(', 'WDFDEVICE inDevice, PFILE_OBJECT inFileObject)', 'WDFFILEOBJECT', '')
call cppapi#function('WdfDeviceGetIoTarget(', 'WDFDEVICE inDevice)', 'WDFIOTARGET', '')
call cppapi#function('WdfDeviceGetSystemPowerAction(', 'WDFDEVICE inDevice)', 'POWER_ACTION', '')
call cppapi#function('WdfDeviceIndicateWakeStatus(', 'WDFDEVICE inDevice, NTSTATUS inWaitWakeStatus)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitAssignName(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inDeviceName)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitAssignSDDLString(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inSDDLString)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitAssignWdmIrpPreprocessCallback(', 'PWDFDEVICE_INIT inDeviceInit, PFN_WDFDEVICE_WDM_IRP_PREPROCESS inEvtDeviceWdmIrpPreprocess, UCHAR inMajorFunction, PUCHAR MinorFunctions, ULONG inNumMinorFunctions)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitFree(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfDeviceInitRegisterPnpStateChangeCallback(', 'PWDFDEVICE_INIT inDeviceInit, WDF_DEVICE_PNP_STATE inPnpState, PFN_WDF_DEVICE_PNP_STATE_CHANGE_NOTIFICATION inEvtDevicePnpStateChange, ULONG inCallbackTypes)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitRegisterPowerPolicyStateChangeCallback(', 'PWDFDEVICE_INIT inDeviceInit, WDF_DEVICE_POWER_POLICY_STATE inPowerPolicyState, PFN_WDF_DEVICE_POWER_POLICY_STATE_CHANGE_NOTIFICATION inEvtDevicePowerPolicyStateChange, ULONG inCallbackTypes)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitRegisterPowerStateChangeCallback(', 'PWDFDEVICE_INIT inDeviceInit, WDF_DEVICE_POWER_STATE inPowerState, PFN_WDF_DEVICE_POWER_STATE_CHANGE_NOTIFICATION inEvtDevicePowerStateChange, ULONG inCallbackTypes)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceInitSetCharacteristics(', 'PWDFDEVICE_INIT inDeviceInit, ULONG inDeviceCharacteristics, BOOLEAN inOrInValues)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetDeviceClass(', 'PWDFDEVICE_INIT inDeviceInit, CONST inGUID* DeviceClassGuid)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetDeviceType(', 'PWDFDEVICE_INIT inDeviceInit, DEVICE_TYPE inDeviceType)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetExclusive(', 'PWDFDEVICE_INIT inDeviceInit, BOOLEAN inIsExclusive)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetFileObjectConfig(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_FILEOBJECT_CONFIG inFileObjectConfig, PWDF_OBJECT_ATTRIBUTES inFileObjectAttributes)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetIoInCallerContextCallback(', 'PWDFDEVICE_INIT inDeviceInit, PFN_WDF_IO_IN_CALLER_CONTEXT inEvtIoInCallerContext)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetIoType(', 'PWDFDEVICE_INIT inDeviceInit, WDF_DEVICE_IO_TYPE inIoType)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPnpPowerEventCallbacks(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_PNPPOWER_EVENT_CALLBACKS inPnpPowerEventCallbacks)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPowerInrush(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPowerNotPageable(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPowerPageable(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPowerPolicyEventCallbacks(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_POWER_POLICY_EVENT_CALLBACKS inPowerPolicyEventCallbacks)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetPowerPolicyOwnership(', 'PWDFDEVICE_INIT inDeviceInit, BOOLEAN inIsPowerPolicyOwner)', 'VOID', '')
call cppapi#function('WdfDeviceInitSetRequestAttributes(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_OBJECT_ATTRIBUTES inRequestAttributes)', 'VOID', '')
call cppapi#function('WdfDeviceMiniportCreate(', 'WDFDRIVER inDriver, PWDF_OBJECT_ATTRIBUTES inAttributes, PDEVICE_OBJECT inDeviceObject, PDEVICE_OBJECT inAttachedDeviceObject, PDEVICE_OBJECT inPdo, outWDFDEVICE* Device)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceOpenRegistryKey(', 'WDFDEVICE inDevice, ULONG inDeviceInstanceKeyType, ACCESS_MASK inDesiredAccess, PWDF_OBJECT_ATTRIBUTES inKeyAttributes, outWDFKEY* Key)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceQueryProperty(', 'WDFDEVICE inDevice, DEVICE_REGISTRY_PROPERTY inDeviceProperty, ULONG inBufferLength, PVOID PropertyBuffer, PULONG outResultLength)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceRemoveDependentUsageDeviceObject(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inDependentDevice)', 'VOID', '')
call cppapi#function('WdfDeviceRemoveRemovalRelationsPhysicalDevice(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inPhysicalDevice)', 'VOID', '')
call cppapi#function('WdfDeviceResumeIdle(', 'WDFDEVICE inDevice)', 'VOID', '')
call cppapi#function('WdfDeviceRetrieveDeviceInterfaceString(', 'WDFDEVICE inDevice, CONST inGUID* InterfaceClassGUID, PCUNICODE_STRING inReferenceString, WDFSTRING inString)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceRetrieveDeviceName(', 'WDFDEVICE inDevice, WDFSTRING inString)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceSetAlignmentRequirement(', 'WDFDEVICE inDevice, ULONG inAlignmentRequirement)', 'VOID', '')
call cppapi#function('WdfDeviceSetBusInformationForChildren(', 'WDFDEVICE inDevice, PPNP_BUS_INFORMATION inBusInformation)', 'VOID', '')
call cppapi#function('WdfDeviceSetCharacteristics(', 'WDFDEVICE inDevice, ULONG inDeviceCharacteristics)', 'VOID', '')
call cppapi#function('WdfDeviceSetDeviceInterfaceState(', 'WDFDEVICE inDevice, CONST inGUID* InterfaceClassGUID, PCUNICODE_STRING inReferenceString, BOOLEAN inIsInterfaceEnabled)', 'VOID', '')
call cppapi#function('WdfDeviceSetDeviceState(', 'WDFDEVICE inDevice, PWDF_DEVICE_STATE inDeviceState)', 'VOID', '')
call cppapi#function('WdfDeviceSetFailed(', 'WDFDEVICE inDevice, WDF_DEVICE_FAILED_ACTION inFailedAction)', 'VOID', '')
call cppapi#function('WdfDeviceSetPnpCapabilities(', 'WDFDEVICE inDevice, PWDF_DEVICE_PNP_CAPABILITIES inPnpCapabilities)', 'VOID', '')
call cppapi#function('WdfDeviceSetPowerCapabilities(', 'WDFDEVICE inDevice, PWDF_DEVICE_POWER_CAPABILITIES inPowerCapabilities)', 'VOID', '')
call cppapi#function('WdfDeviceSetSpecialFileSupport(', 'WDFDEVICE inDevice, WDF_SPECIAL_FILE_TYPE inFileType, BOOLEAN inFileTypeIsSupported)', 'VOID', '')
call cppapi#function('WdfDeviceSetStaticStopRemove(', 'WDFDEVICE inDevice, BOOLEAN inStoppable)', 'VOID', '')
call cppapi#function('WdfDeviceWdmDispatchPreprocessedIrp(', 'WDFDEVICE inDevice, PIRP inIrp)', 'NTSTATUS', '')
call cppapi#function('WdfDeviceWdmGetAttachedDevice(', 'WDFDEVICE inDevice)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfDeviceWdmGetDeviceObject(', 'WDFDEVICE inDevice)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfDeviceWdmGetPhysicalDevice(', 'WDFDEVICE inDevice)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfDmaEnablerCreate(', 'WDFDEVICE inDevice, PWDF_DMA_ENABLER_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFDMAENABLER* DmaEnablerHandle)', 'NTSTATUS', '')
call cppapi#function('WdfDmaEnablerGetFragmentLength(', 'WDFDMAENABLER inDmaEnabler, WDF_DMA_DIRECTION inDmaDirection)', 'size_t', '')
call cppapi#function('WdfDmaEnablerGetMaximumLength(', 'WDFDMAENABLER inDmaEnabler)', 'size_t', '')
call cppapi#function('WdfDmaEnablerGetMaximumScatterGatherElements(', 'WDFDMAENABLER inDmaEnabler)', 'size_t', '')
call cppapi#function('WdfDmaEnablerSetMaximumScatterGatherElements(', 'WDFDMAENABLER inDmaEnabler, size_t inMaximumFragments)', 'VOID', '')
call cppapi#function('WdfDmaEnablerWdmGetDmaAdapter(', 'WDFDMAENABLER inDmaEnabler, WDF_DMA_DIRECTION inDmaDirection)', 'PDMA_ADAPTER', '')
call cppapi#function('WdfDmaTransactionCreate(', 'WDFDMAENABLER inDmaEnabler, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFDMATRANSACTION* DmaTransaction)', 'NTSTATUS', '')
call cppapi#function('WdfDmaTransactionDmaCompleted(', 'WDFDMATRANSACTION inDmaTransaction, outNTSTATUS* Status)', 'BOOLEAN', '')
call cppapi#function('WdfDmaTransactionDmaCompletedFinal(', 'WDFDMATRANSACTION inDmaTransaction, size_t inFinalTransferredLength, outNTSTATUS* Status)', 'BOOLEAN', '')
call cppapi#function('WdfDmaTransactionDmaCompletedWithLength(', 'WDFDMATRANSACTION inDmaTransaction, size_t inTransferredLength, outNTSTATUS* Status)', 'BOOLEAN', '')
call cppapi#function('WdfDmaTransactionExecute(', 'WDFDMATRANSACTION inDmaTransaction, WDFCONTEXT inContext)', 'NTSTATUS', '')
call cppapi#function('WdfDmaTransactionGetBytesTransferred(', 'WDFDMATRANSACTION inDmaTransaction)', 'size_t', '')
call cppapi#function('WdfDmaTransactionGetCurrentDmaTransferLength(', 'WDFDMATRANSACTION inDmaTransaction)', 'size_t', '')
call cppapi#function('WdfDmaTransactionGetDevice(', 'WDFDMATRANSACTION inDmaTransaction)', 'WDFDEVICE', '')
call cppapi#function('WdfDmaTransactionGetRequest(', 'WDFDMATRANSACTION inDmaTransaction)', 'WDFREQUEST', '')
call cppapi#function('WdfDmaTransactionInitialize(', 'WDFDMATRANSACTION inDmaTransaction, PFN_WDF_PROGRAM_DMA inEvtProgramDmaFunction, WDF_DMA_DIRECTION inDmaDirection, PMDL inMdl, PVOID inVirtualAddress, size_t inLength)', 'NTSTATUS', '')
call cppapi#function('WdfDmaTransactionInitializeUsingRequest(', 'WDFDMATRANSACTION inDmaTransaction, WDFREQUEST inRequest, PFN_WDF_PROGRAM_DMA inEvtProgramDmaFunction, WDF_DMA_DIRECTION inDmaDirection)', 'NTSTATUS', '')
call cppapi#function('WdfDmaTransactionRelease(', 'WDFDMATRANSACTION inDmaTransaction)', 'NTSTATUS', '')
call cppapi#function('WdfDmaTransactionSetMaximumLength(', 'WDFDMATRANSACTION inDmaTransaction, size_t inMaximumLength)', 'VOID', '')
call cppapi#function('WdfDpcCancel(', 'WDFDPC inDpc, BOOLEAN inWait)', 'BOOLEAN', '')
call cppapi#function('WdfDpcCreate(', 'PWDF_DPC_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFDPC* Dpc)', 'NTSTATUS', '')
call cppapi#function('WdfDpcEnqueue(', 'WDFDPC inDpc)', 'BOOLEAN', '')
call cppapi#function('WdfDpcGetParentObject(', 'WDFDPC inDpc)', 'WDFOBJECT', '')
call cppapi#function('WdfDpcWdmGetDpc(', 'WDFDPC inDpc)', 'PKDPC', '')
call cppapi#function('WdfDriverCreate(', 'PDRIVER_OBJECT inDriverObject, PCUNICODE_STRING inRegistryPath, PWDF_OBJECT_ATTRIBUTES inDriverAttributes, PWDF_DRIVER_CONFIG inDriverConfig, outWDFDRIVER* Driver)', 'NTSTATUS', '')
call cppapi#function('WdfDriverGetRegistryPath(', 'WDFDRIVER inDriver)', 'PWSTR', '')
call cppapi#function('WdfDriverIsVersionAvailable(', 'WDFDRIVER inDriver, PWDF_DRIVER_VERSION_AVAILABLE_PARAMS inVersionAvailableParams)', 'BOOLEAN', '')
call cppapi#function('WdfDriverOpenParametersRegistryKey(', 'WDFDRIVER inDriver, ACCESS_MASK inDesiredAccess, PWDF_OBJECT_ATTRIBUTES inKeyAttributes, outWDFKEY* Key)', 'NTSTATUS', '')
call cppapi#function('WdfDriverRegisterTraceInfo(', 'PDRIVER_OBJECT inDriverObject, PFN_WDF_TRACE_CALLBACK inEvtTraceCallback, PVOID inControlBlock)', 'NTSTATUS', '')
call cppapi#function('WdfDriverRetrieveVersionString(', 'WDFDRIVER inDriver, WDFSTRING inString)', 'NTSTATUS', '')
call cppapi#function('WdfDriverWdmGetDriverObject(', 'WDFDRIVER inDriver)', 'PDRIVER_OBJECT', '')
call cppapi#function('WdfFdoAddStaticChild(', 'WDFDEVICE inFdo, WDFDEVICE inChild)', 'NTSTATUS', '')
call cppapi#function('WdfFdoGetDefaultChildList(', 'WDFDEVICE inFdo)', 'WDFCHILDLIST', '')
call cppapi#function('WdfFdoInitAllocAndQueryProperty(', 'PWDFDEVICE_INIT inDeviceInit, DEVICE_REGISTRY_PROPERTY inDeviceProperty, POOL_TYPE inPoolType, PWDF_OBJECT_ATTRIBUTES inPropertyMemoryAttributes, outWDFMEMORY* PropertyMemory)', 'NTSTATUS', '')
call cppapi#function('WdfFdoInitOpenRegistryKey(', 'PWDFDEVICE_INIT inDeviceInit, ULONG inDeviceInstanceKeyType, ACCESS_MASK inDesiredAccess, PWDF_OBJECT_ATTRIBUTES inKeyAttributes, outWDFKEY* Key)', 'NTSTATUS', '')
call cppapi#function('WdfFdoInitQueryProperty(', 'PWDFDEVICE_INIT inDeviceInit, DEVICE_REGISTRY_PROPERTY inDeviceProperty, ULONG inBufferLength, PVOID PropertyBuffer, PULONG outResultLength)', 'NTSTATUS', '')
call cppapi#function('WdfFdoInitSetDefaultChildListConfig(', 'PWDFDEVICE_INIT ioDeviceInit, PWDF_CHILD_LIST_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inDefaultChildListAttributes)', 'VOID', '')
call cppapi#function('WdfFdoInitSetEventCallbacks(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_FDO_EVENT_CALLBACKS inFdoEventCallbacks)', 'VOID', '')
call cppapi#function('WdfFdoInitSetFilter(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfFdoInitWdmGetPhysicalDevice(', 'PWDFDEVICE_INIT inDeviceInit)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfFdoLockStaticChildListForIteration(', 'WDFDEVICE inFdo)', 'VOID', '')
call cppapi#function('WdfFdoQueryForInterface(', 'WDFDEVICE inFdo, LPCGUID inInterfaceType, PINTERFACE outInterface, USHORT inSize, USHORT inVersion, PVOID inInterfaceSpecificData)', 'NTSTATUS', '')
call cppapi#function('WdfFdoRetrieveNextStaticChild(', 'WDFDEVICE inFdo, WDFDEVICE inPreviousChild, ULONG inFlags)', 'WDFDEVICE', '')
call cppapi#function('WdfFdoUnlockStaticChildListFromIteration(', 'WDFDEVICE inFdo)', 'VOID', '')
call cppapi#function('WdfFileObjectGetDevice(', 'WDFFILEOBJECT inFileObject)', 'WDFDEVICE', '')
call cppapi#function('WdfFileObjectGetFileName(', 'WDFFILEOBJECT inFileObject)', 'PUNICODE_STRING', '')
call cppapi#function('WdfFileObjectGetFlags(', 'WDFFILEOBJECT inFileObject)', 'ULONG', '')
call cppapi#function('WdfFileObjectWdmGetFileObject(', 'WDFFILEOBJECT inFileObject)', 'PFILE_OBJECT', '')
call cppapi#function('WdfInterruptAcquireLock(', 'WDFINTERRUPT inInterrupt)', 'VOID', '')
call cppapi#function('WdfInterruptCreate(', 'WDFDEVICE inDevice, PWDF_INTERRUPT_CONFIG inConfiguration, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFINTERRUPT* Interrupt)', 'NTSTATUS', '')
call cppapi#function('WdfInterruptDisable(', 'WDFINTERRUPT inInterrupt)', 'VOID', '')
call cppapi#function('WdfInterruptEnable(', 'WDFINTERRUPT inInterrupt)', 'VOID', '')
call cppapi#function('WdfInterruptGetInfo(', 'WDFINTERRUPT inInterrupt, PWDF_INTERRUPT_INFO outInfo)', 'VOID', '')
call cppapi#function('WdfInterruptReleaseLock(', 'WDFINTERRUPT inInterrupt)', 'VOID', '')
call cppapi#function('WdfInterruptSetExtendedPolicy(', 'WDFINTERRUPT inInterrupt, PWDF_INTERRUPT_EXTENDED_POLICY inPolicyAndGroup)', 'VOID', '')
call cppapi#function('WdfInterruptSetPolicy(', 'WDFINTERRUPT inInterrupt, WDF_INTERRUPT_POLICY inPolicy, WDF_INTERRUPT_PRIORITY inPriority, KAFFINITY inTargetProcessorSet)', 'VOID', '')
call cppapi#function('WdfInterruptSynchronize(', 'WDFINTERRUPT inInterrupt, PFN_WDF_INTERRUPT_SYNCHRONIZE inCallback, WDFCONTEXT inContext)', 'BOOLEAN', '')
call cppapi#function('WdfIoQueueAssignForwardProgressPolicy(', 'WDFQUEUE inQueue, PWDF_IO_QUEUE_FORWARD_PROGRESS_POLICY inForwardProgressPolicy)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueCreate(', 'WDFDEVICE inDevice, PWDF_IO_QUEUE_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inQueueAttributes, outWDFQUEUE* Queue)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueDrain(', 'WDFQUEUE inQueue, PFN_WDF_IO_QUEUE_STATE DrainComplete, WDFCONTEXT Context)', 'VOID', '')
call cppapi#function('WdfIoQueueDrainSynchronously(', 'WDFQUEUE inQueue)', 'VOID', '')
call cppapi#function('WdfIoQueueFindRequest(', 'WDFQUEUE inQueue, WDFREQUEST inFoundRequest, WDFFILEOBJECT inFileObject, PWDF_REQUEST_PARAMETERS ioParameters, outWDFREQUEST* OutRequest)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueGetDevice(', 'WDFQUEUE inQueue)', 'WDFDEVICE', '')
call cppapi#function('WdfIoQueueGetState(', 'WDFQUEUE inQueue, PULONG outQueueRequests, PULONG outDriverRequests)', 'WDF_IO_QUEUE_STATE', '')
call cppapi#function('WdfIoQueuePurge(', 'WDFQUEUE inQueue, PFN_WDF_IO_QUEUE_STATE PurgeComplete, WDFCONTEXT Context)', 'VOID', '')
call cppapi#function('WdfIoQueuePurgeSynchronously(', 'WDFQUEUE inQueue)', 'VOID', '')
call cppapi#function('WdfIoQueueReadyNotify(', 'WDFQUEUE inQueue, PFN_WDF_IO_QUEUE_STATE inQueueReady, WDFCONTEXT inContext)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueRetrieveFoundRequest(', 'WDFQUEUE inQueue, WDFREQUEST inFoundRequest, outWDFREQUEST* OutRequest)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueRetrieveNextRequest(', 'WDFQUEUE inQueue, outWDFREQUEST* OutRequest)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueRetrieveRequestByFileObject(', 'WDFQUEUE inQueue, WDFFILEOBJECT inFileObject, outWDFREQUEST* OutRequest)', 'NTSTATUS', '')
call cppapi#function('WdfIoQueueStart(', 'WDFQUEUE inQueue)', 'VOID', '')
call cppapi#function('WdfIoQueueStop(', 'WDFQUEUE inQueue, PFN_WDF_IO_QUEUE_STATE StopComplete, WDFCONTEXT Context)', 'VOID', '')
call cppapi#function('WdfIoQueueStopSynchronously(', 'WDFQUEUE inQueue)', 'VOID', '')
call cppapi#function('WdfIoResourceListAppendDescriptor(', 'WDFIORESLIST inResourceList, PIO_RESOURCE_DESCRIPTOR inDescriptor)', 'NTSTATUS', '')
call cppapi#function('WdfIoResourceListCreate(', 'WDFIORESREQLIST inRequirementsList, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFIORESLIST* ResourceList)', 'NTSTATUS', '')
call cppapi#function('WdfIoResourceListGetCount(', 'WDFIORESLIST inResourceList)', 'ULONG', '')
call cppapi#function('WdfIoResourceListGetDescriptor(', 'WDFIORESLIST inResourceList, ULONG inIndex)', 'PIO_RESOURCE_DESCRIPTOR', '')
call cppapi#function('WdfIoResourceListInsertDescriptor(', 'WDFIORESLIST inResourceList, PIO_RESOURCE_DESCRIPTOR inDescriptor, ULONG inIndex)', 'NTSTATUS', '')
call cppapi#function('WdfIoResourceListRemove(', 'WDFIORESLIST inResourceList, ULONG inIndex)', 'VOID', '')
call cppapi#function('WdfIoResourceListRemoveByDescriptor(', 'WDFIORESLIST inResourceList, PIO_RESOURCE_DESCRIPTOR inDescriptor)', 'VOID', '')
call cppapi#function('WdfIoResourceListUpdateDescriptor(', 'WDFIORESLIST inResourceList, PIO_RESOURCE_DESCRIPTOR inDescriptor, ULONG inIndex)', 'VOID', '')
call cppapi#function('WdfIoResourceRequirementsListAppendIoResList(', 'WDFIORESREQLIST inRequirementsList, WDFIORESLIST inIoResList)', 'NTSTATUS', '')
call cppapi#function('WdfIoResourceRequirementsListGetCount(', 'WDFIORESREQLIST inRequirementsList)', 'ULONG', '')
call cppapi#function('WdfIoResourceRequirementsListGetIoResList(', 'WDFIORESREQLIST inRequirementsList, ULONG inIndex)', 'WDFIORESLIST', '')
call cppapi#function('WdfIoResourceRequirementsListInsertIoResList(', 'WDFIORESREQLIST inRequirementsList, WDFIORESLIST inIoResList, ULONG inIndex)', 'NTSTATUS', '')
call cppapi#function('WdfIoResourceRequirementsListRemove(', 'WDFIORESREQLIST inRequirementsList, ULONG inIndex)', 'VOID', '')
call cppapi#function('WdfIoResourceRequirementsListRemoveByIoResList(', 'WDFIORESREQLIST inRequirementsList, WDFIORESLIST inIoResList)', 'VOID', '')
call cppapi#function('WdfIoResourceRequirementsListSetInterfaceType(', 'WDFIORESREQLIST inRequirementsList, INTERFACE_TYPE inInterfaceType)', 'VOID', '')
call cppapi#function('WdfIoResourceRequirementsListSetSlotNumber(', 'WDFIORESREQLIST inRequirementsList, ULONG inSlotNumber)', 'VOID', '')
call cppapi#function('WdfIoTargetAllocAndQueryTargetProperty(', 'WDFIOTARGET inIoTarget, DEVICE_REGISTRY_PROPERTY inDeviceProperty, POOL_TYPE inPoolType, PWDF_OBJECT_ATTRIBUTES inPropertyMemoryAttributes, outWDFMEMORY* PropertyMemory)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetClose(', 'WDFIOTARGET inIoTarget)', 'VOID', '')
call cppapi#function('WdfIoTargetCloseForQueryRemove(', 'WDFIOTARGET inIoTarget)', 'VOID', '')
call cppapi#function('WdfIoTargetCreate(', 'WDFDEVICE inDevice, PWDF_OBJECT_ATTRIBUTES inIoTargetAttributes, outWDFIOTARGET* IoTarget)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetFormatRequestForInternalIoctl(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG IoctlCode, WDFMEMORY inInputBuffer, PWDFMEMORY_OFFSET inInputBufferOffset, WDFMEMORY inOutputBuffer, PWDFMEMORY_OFFSET inOutputBufferOffset)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetFormatRequestForInternalIoctlOthers(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG IoctlCode, WDFMEMORY inOtherArg1, PWDFMEMORY_OFFSET inOtherArg1Offset, WDFMEMORY inOtherArg2, PWDFMEMORY_OFFSET inOtherArg2Offset, WDFMEMORY inOtherArg4, PWDFMEMORY_OFFSET inOtherArg4Offset)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetFormatRequestForIoctl(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG IoctlCode, WDFMEMORY inInputBuffer, PWDFMEMORY_OFFSET inInputBufferOffset, WDFMEMORY inOutputBuffer, PWDFMEMORY_OFFSET inOutputBufferOffset)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetFormatRequestForRead(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, WDFMEMORY inOutputBuffer, PWDFMEMORY_OFFSET inOutputBufferOffset, PLONGLONG inDeviceOffset)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetFormatRequestForWrite(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, WDFMEMORY inInputBuffer, PWDFMEMORY_OFFSET inInputBufferOffset, PLONGLONG inDeviceOffset)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetGetDevice(', 'WDFIOTARGET inIoTarget)', 'WDFDEVICE', '')
call cppapi#function('WdfIoTargetGetState(', 'WDFIOTARGET inIoTarget)', 'WDF_IO_TARGET_STATE', '')
call cppapi#function('WdfIoTargetOpen(', 'WDFIOTARGET inIoTarget, PWDF_IO_TARGET_OPEN_PARAMS inOpenParams)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetQueryForInterface(', 'WDFIOTARGET inIoTarget, LPCGUID inInterfaceType, PINTERFACE outInterface, USHORT inSize, USHORT inVersion, PVOID inInterfaceSpecificData)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetQueryTargetProperty(', 'WDFIOTARGET inIoTarget, DEVICE_REGISTRY_PROPERTY inDeviceProperty, ULONG inBufferLength, PVOID PropertyBuffer, PULONG ResultLength)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetSendInternalIoctlOthersSynchronously(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG IoctlCode, PWDF_MEMORY_DESCRIPTOR inOtherArg1, PWDF_MEMORY_DESCRIPTOR inOtherArg2, PWDF_MEMORY_DESCRIPTOR inOtherArg4, PWDF_REQUEST_SENDIONS inRequestOptions, PULONG_PTR outBytesReturned)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetSendInternalIoctlSynchronously(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG inIoctlCode, PWDF_MEMORY_DESCRIPTOR inInputBuffer, PWDF_MEMORY_DESCRIPTOR inOutputBuffer, PWDF_REQUEST_SENDIONS inRequestOptions, PULONG_PTR outBytesReturned)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetSendIoctlSynchronously(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, ULONG inIoctlCode, PWDF_MEMORY_DESCRIPTOR inInputBuffer, PWDF_MEMORY_DESCRIPTOR inOutputBuffer, PWDF_REQUEST_SENDIONS inRequestOptions, PULONG_PTR outBytesReturned)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetSendReadSynchronously(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, PWDF_MEMORY_DESCRIPTOR inOutputBuffer, PLONGLONG inDeviceOffset, PWDF_REQUEST_SENDIONS inRequestOptions, PULONG_PTR outBytesRead)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetSendWriteSynchronously(', 'WDFIOTARGET inIoTarget, WDFREQUEST inRequest, PWDF_MEMORY_DESCRIPTOR inInputBuffer, PLONGLONG inDeviceOffset, PWDF_REQUEST_SENDIONS inRequestOptions, PULONG_PTR outBytesWritten)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetStart(', 'WDFIOTARGET inIoTarget)', 'NTSTATUS', '')
call cppapi#function('WdfIoTargetStop(', 'WDFIOTARGET inIoTarget, WDF_IO_TARGET_SENT_IO_ACTION inAction)', 'VOID', '')
call cppapi#function('WdfIoTargetWdmGetTargetDeviceObject(', 'WDFIOTARGET inIoTarget)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfIoTargetWdmGetTargetFileHandle(', 'WDFIOTARGET inIoTarget)', 'HANDLE', '')
call cppapi#function('WdfIoTargetWdmGetTargetFileObject(', 'WDFIOTARGET inIoTarget)', 'PFILE_OBJECT', '')
call cppapi#function('WdfIoTargetWdmGetTargetPhysicalDevice(', 'WDFIOTARGET inIoTarget)', 'PDEVICE_OBJECT', '')
call cppapi#function('WdfLookasideListCreate(', 'PWDF_OBJECT_ATTRIBUTES inLookasideAttributes, size_t inBufferSize, POOL_TYPE inPoolType, PWDF_OBJECT_ATTRIBUTES inMemoryAttributes, ULONG inPoolTag, outWDFLOOKASIDE* Lookaside)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryAssignBuffer(', 'WDFMEMORY inMemory, PVOID inBuffer, size_t inBufferSize)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryCopyFromBuffer(', 'WDFMEMORY inDestinationMemory, size_t inDestinationOffset, PVOID inBuffer, size_t inNumBytesToCopyFrom)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryCopyToBuffer(', 'WDFMEMORY inSourceMemory, size_t inSourceOffset, PVOID Buffer, size_t inNumBytesToCopyTo)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryCreate(', 'PWDF_OBJECT_ATTRIBUTES inAttributes, POOL_TYPE inPoolType, ULONG inPoolTag, size_t inBufferSize, outWDFMEMORY* Memory, outPVOID* Buffer)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryCreateFromLookaside(', 'WDFLOOKASIDE inLookaside, outWDFMEMORY* Memory)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryCreatePreallocated(', 'PWDF_OBJECT_ATTRIBUTES inAttributes, size_t inBufferSize, outWDFMEMORY* Memory)', 'NTSTATUS', '')
call cppapi#function('WdfMemoryGetBuffer(', 'WDFMEMORY inMemory, outsize_t* BufferSize)', 'PVOID', '')
call cppapi#function('WdfObjectAcquireLock(', 'WDFOBJECT inObject)', 'VOID', '')
call cppapi#function('WdfObjectCreate(', 'PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFOBJECT* Object)', 'NTSTATUS', '')
call cppapi#function('WdfObjectDelete(', 'WDFOBJECT inObject)', 'VOID', '')
call cppapi#function('WdfObjectQuery(', 'WDFOBJECT inObject, CONST inGUID* Guid, ULONG inQueryBufferLength, PVOID QueryBuffer)', 'NTSTATUS', '')
call cppapi#function('WdfObjectReleaseLock(', 'WDFOBJECT inObject)', 'VOID', '')
call cppapi#function('WdfPdoAddEjectionRelationsPhysicalDevice(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inPhysicalDevice)', 'NTSTATUS', '')
call cppapi#function('WdfPdoClearEjectionRelationsDevices(', 'WDFDEVICE inDevice)', 'VOID', '')
call cppapi#function('WdfPdoGetParent(', 'WDFDEVICE inDevice)', 'WDFDEVICE', '')
call cppapi#function('WdfPdoInitAddCompatibleID(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inCompatibleID)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAddDeviceText(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inDeviceDescription, PCUNICODE_STRING inDeviceLocation, LCID inLocaleId)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAddHardwareID(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inHardwareID)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAllocate(', 'WDFDEVICE inParentDevice)', 'PWDFDEVICE_INIT', '')
call cppapi#function('WdfPdoInitAllowForwardingRequestToParent(', 'PWDFDEVICE_INIT inDeviceInit)', 'VOID', '')
call cppapi#function('WdfPdoInitAssignContainerID(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inContainerID)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAssignDeviceID(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inDeviceID)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAssignInstanceID(', 'PWDFDEVICE_INIT inDeviceInit, PCUNICODE_STRING inInstanceID)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitAssignRawDevice(', 'PWDFDEVICE_INIT inDeviceInit, CONST inGUID* DeviceClassGuid)', 'NTSTATUS', '')
call cppapi#function('WdfPdoInitSetDefaultLocale(', 'PWDFDEVICE_INIT inDeviceInit, LCID inLocaleId)', 'VOID', '')
call cppapi#function('WdfPdoInitSetEventCallbacks(', 'PWDFDEVICE_INIT inDeviceInit, PWDF_PDO_EVENT_CALLBACKS inDispatchTable)', 'VOID', '')
call cppapi#function('WdfPdoMarkMissing(', 'WDFDEVICE inDevice)', 'NTSTATUS', '')
call cppapi#function('WdfPdoRemoveEjectionRelationsPhysicalDevice(', 'WDFDEVICE inDevice, PDEVICE_OBJECT inPhysicalDevice)', 'VOID', '')
call cppapi#function('WdfPdoRequestEject(', 'WDFDEVICE inDevice)', 'VOID', '')
call cppapi#function('WdfPdoRetrieveAddressDescription(', 'WDFDEVICE inDevice, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER ioAddressDescription)', 'NTSTATUS', '')
call cppapi#function('WdfPdoRetrieveIdentificationDescription(', 'WDFDEVICE inDevice, PWDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER ioIdentificationDescription)', 'NTSTATUS', '')
call cppapi#function('WdfPdoUpdateAddressDescription(', 'WDFDEVICE inDevice, PWDF_CHILD_ADDRESS_DESCRIPTION_HEADER ioAddressDescription)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignMemory(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, ULONG inValueType, WDFMEMORY inMemory, PWDFMEMORY_OFFSET inMemoryOffsets)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignMultiString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, WDFCOLLECTION inStringsCollection)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, WDFSTRING inString)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignULong(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, ULONG inValue)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignUnicodeString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, PCUNICODE_STRING inValue)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryAssignValue(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, ULONG inValueType, ULONG inValueLength, PVOID Value)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryClose(', 'WDFKEY inKey)', 'VOID', '')
call cppapi#function('WdfRegistryCreateKey(', 'WDFKEY inParentKey, PCUNICODE_STRING inKeyName, ACCESS_MASK inDesiredAccess, ULONG inCreateOptions, PULONG outCreateDisposition, PWDF_OBJECT_ATTRIBUTES inKeyAttributes, outWDFKEY* Key)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryOpenKey(', 'WDFKEY inParentKey, PCUNICODE_STRING inKeyName, ACCESS_MASK inDesiredAccess, PWDF_OBJECT_ATTRIBUTES inKeyAttributes, outWDFKEY* Key)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryMemory(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, POOL_TYPE inPoolType, PWDF_OBJECT_ATTRIBUTES inMemoryAttributes, outWDFMEMORY* Memory, PULONG outValueType)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryMultiString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, PWDF_OBJECT_ATTRIBUTES inStringsAttributes, WDFCOLLECTION inCollection)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, WDFSTRING inString)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryULong(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, PULONG outValue)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryUnicodeString(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, PUSHORT outValueByteLength, PUNICODE_STRING ioValue)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryQueryValue(', 'WDFKEY inKey, PCUNICODE_STRING inValueName, ULONG inValueLength, PVOID Value, PULONG outValueLengthQueried, PULONG outValueType)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryRemoveKey(', 'WDFKEY inKey)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryRemoveValue(', 'WDFKEY inKey, PCUNICODE_STRING inValueName)', 'NTSTATUS', '')
call cppapi#function('WdfRegistryWdmGetHandle(', 'WDFKEY inKey)', 'HANDLE', '')
call cppapi#function('WdfRequestAllocateTimer(', 'WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfRequestCancelSentRequest(', 'WDFREQUEST inRequest)', 'BOOLEAN', '')
call cppapi#function('WdfRequestChangeTarget(', 'WDFREQUEST inRequest, WDFIOTARGET inIoTarget)', 'NTSTATUS', '')
call cppapi#function('WdfRequestComplete(', 'WDFREQUEST inRequest, NTSTATUS inStatus)', 'VOID', '')
call cppapi#function('WdfRequestCompleteWithInformation(', 'WDFREQUEST inRequest, NTSTATUS inStatus, ULONG_PTR inInformation)', 'VOID', '')
call cppapi#function('WdfRequestCompleteWithPriorityBoost(', 'WDFREQUEST inRequest, NTSTATUS inStatus, CCHAR inPriorityBoost)', 'VOID', '')
call cppapi#function('WdfRequestCreate(', 'PWDF_OBJECT_ATTRIBUTES inRequestAttributes, WDFIOTARGET inIoTarget, outWDFREQUEST* Request)', 'NTSTATUS', '')
call cppapi#function('WdfRequestCreateFromIrp(', 'PWDF_OBJECT_ATTRIBUTES inRequestAttributes, PIRP inIrp, BOOLEAN inRequestFreesIrp, outWDFREQUEST* Request)', 'NTSTATUS', '')
call cppapi#function('WdfRequestFormatRequestUsingCurrentType(', 'WDFREQUEST inRequest)', 'VOID', '')
call cppapi#function('WdfRequestForwardToIoQueue(', 'WDFREQUEST inRequest, WDFQUEUE inDestinationQueue)', 'NTSTATUS', '')
call cppapi#function('WdfRequestForwardToParentDeviceIoQueue(', 'WDFREQUEST inRequest, WDFQUEUE inParentDeviceQueue, PWDF_REQUEST_FORWARDIONS inForwardOptions)', 'NTSTATUS', '')
call cppapi#function('WdfRequestGetCompletionParams(', 'WDFREQUEST inRequest, PWDF_REQUEST_COMPLETION_PARAMS outParams)', 'VOID', '')
call cppapi#function('WdfRequestGetFileObject(', 'WDFREQUEST inRequest)', 'WDFFILEOBJECT', '')
call cppapi#function('WdfRequestGetInformation(', 'WDFREQUEST inRequest)', 'ULONG_PTR', '')
call cppapi#function('WdfRequestGetIoQueue(', 'WDFREQUEST inRequest)', 'WDFQUEUE', '')
call cppapi#function('WdfRequestGetParameters(', 'WDFREQUEST inRequest, PWDF_REQUEST_PARAMETERS outParameters)', 'VOID', '')
call cppapi#function('WdfRequestGetRequestorMode(', 'WDFREQUEST inRequest)', 'KPROCESSOR_MODE', '')
call cppapi#function('WdfRequestGetStatus(', 'WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfRequestIsCanceled(', 'WDFREQUEST inRequest)', 'BOOLEAN', '')
call cppapi#function('WdfRequestIsFrom32BitProcess(', 'WDFREQUEST inRequest)', 'BOOLEAN', '')
call cppapi#function('WdfRequestIsReserved(', 'WDFREQUEST inRequest)', 'BOOLEAN', '')
call cppapi#function('WdfRequestMarkCancelable(', 'WDFREQUEST inRequest, PFN_WDF_REQUEST_CANCEL inEvtRequestCancel)', 'VOID', '')
call cppapi#function('WdfRequestMarkCancelableEx(', 'WDFREQUEST inRequest, PFN_WDF_REQUEST_CANCEL inEvtRequestCancel)', 'NTSTATUS', '')
call cppapi#function('WdfRequestProbeAndLockUserBufferForRead(', 'WDFREQUEST inRequest, PVOID Buffer, size_t inLength, outWDFMEMORY* MemoryObject)', 'NTSTATUS', '')
call cppapi#function('WdfRequestProbeAndLockUserBufferForWrite(', 'WDFREQUEST inRequest, PVOID Buffer, size_t inLength, outWDFMEMORY* MemoryObject)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRequeue(', 'WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveInputBuffer(', 'WDFREQUEST inRequest, size_t inMinimumRequiredLength, PVOID* Buffer, outsize_t* Length)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveInputMemory(', 'WDFREQUEST inRequest, outWDFMEMORY* Memory)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveInputWdmMdl(', 'WDFREQUEST inRequest, PMDL* Mdl)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveOutputBuffer(', 'WDFREQUEST inRequest, size_t inMinimumRequiredSize, PVOID* Buffer, outsize_t* Length)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveOutputMemory(', 'WDFREQUEST inRequest, outWDFMEMORY* Memory)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveOutputWdmMdl(', 'WDFREQUEST inRequest, PMDL* Mdl)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveUnsafeUserInputBuffer(', 'WDFREQUEST inRequest, size_t inMinimumRequiredLength, PVOID* InputBuffer, outsize_t* Length)', 'NTSTATUS', '')
call cppapi#function('WdfRequestRetrieveUnsafeUserOutputBuffer(', 'WDFREQUEST inRequest, size_t inMinimumRequiredLength, PVOID* OutputBuffer, outsize_t* Length)', 'NTSTATUS', '')
call cppapi#function('WdfRequestReuse(', 'WDFREQUEST inRequest, PWDF_REQUEST_REUSE_PARAMS inReuseParams)', 'NTSTATUS', '')
call cppapi#function('WdfRequestSend(', 'WDFREQUEST inRequest, WDFIOTARGET inTarget, PWDF_REQUEST_SENDIONS inOptions)', 'BOOLEAN', '')
call cppapi#function('WdfRequestSetCompletionRoutine(', 'WDFREQUEST inRequest, PFN_WDF_REQUEST_COMPLETION_ROUTINE inCompletionRoutine, WDFCONTEXT inCompletionContext)', 'VOID', '')
call cppapi#function('WdfRequestSetInformation(', 'WDFREQUEST inRequest, ULONG_PTR inInformation)', 'VOID', '')
call cppapi#function('WdfRequestStopAcknowledge(', 'WDFREQUEST inRequest, BOOLEAN inRequeue)', 'VOID', '')
call cppapi#function('WdfRequestUnmarkCancelable(', 'WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfRequestWdmFormatUsingStackLocation(', 'WDFREQUEST inRequest, PIO_STACK_LOCATION inStack)', 'VOID', '')
call cppapi#function('WdfRequestWdmGetIrp(', 'WDFREQUEST inRequest)', 'PIRP', '')
call cppapi#function('WdfSpinLockAcquire(', 'WDFSPINLOCK inSpinLock)', 'VOID', '')
call cppapi#function('WdfSpinLockCreate(', 'PWDF_OBJECT_ATTRIBUTES inSpinLockAttributes, outWDFSPINLOCK* SpinLock)', 'NTSTATUS', '')
call cppapi#function('WdfSpinLockRelease(', 'WDFSPINLOCK inSpinLock)', 'VOID', '')
call cppapi#function('WdfStringCreate(', 'PCUNICODE_STRING inUnicodeString, PWDF_OBJECT_ATTRIBUTES inStringAttributes, outWDFSTRING* String)', 'NTSTATUS', '')
call cppapi#function('WdfStringGetUnicodeString(', 'WDFSTRING inString, PUNICODE_STRING outUnicodeString)', 'VOID', '')
call cppapi#function('WdfTimerCreate(', 'PWDF_TIMER_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFTIMER* Timer)', 'NTSTATUS', '')
call cppapi#function('WdfTimerGetParentObject(', 'WDFTIMER inTimer)', 'WDFOBJECT', '')
call cppapi#function('WdfTimerStart(', 'WDFTIMER inTimer, LONGLONG inDueTime)', 'BOOLEAN', '')
call cppapi#function('WdfTimerStop(', 'WDFTIMER inTimer, BOOLEAN inWait)', 'BOOLEAN', '')
call cppapi#function('WdfUsbInterfaceGetConfiguredPipe(', 'WDFUSBINTERFACE inUsbInterface, UCHAR inPipeIndex, PWDF_USB_PIPE_INFORMATION outPipeInfo)', 'WDFUSBPIPE', '')
call cppapi#function('WdfUsbInterfaceGetConfiguredSettingIndex(', 'WDFUSBINTERFACE inInterface)', 'BYTE', '')
call cppapi#function('WdfUsbInterfaceGetDescriptor(', 'WDFUSBINTERFACE inUsbInterface, UCHAR inSettingIndex, PUSB_INTERFACE_DESCRIPTOR outInterfaceDescriptor)', 'VOID', '')
call cppapi#function('WdfUsbInterfaceGetEndpointInformation(', 'WDFUSBINTERFACE inUsbInterface, UCHAR inSettingIndex, UCHAR inEndpointIndex, PWDF_USB_PIPE_INFORMATION outEndpointInfo)', 'VOID', '')
call cppapi#function('WdfUsbInterfaceGetInterfaceNumber(', 'WDFUSBINTERFACE inUsbInterface)', 'BYTE', '')
call cppapi#function('WdfUsbInterfaceGetNumConfiguredPipes(', 'WDFUSBINTERFACE inUsbInterface)', 'BYTE', '')
call cppapi#function('WdfUsbInterfaceGetNumEndpoints(', 'WDFUSBINTERFACE inUsbInterface, UCHAR inSettingIndex)', 'BYTE', '')
call cppapi#function('WdfUsbInterfaceGetNumSettings(', 'WDFUSBINTERFACE inUsbInterface)', 'BYTE', '')
call cppapi#function('WdfUsbInterfaceSelectSetting(', 'WDFUSBINTERFACE inUsbInterface, PWDF_OBJECT_ATTRIBUTES inPipesAttributes, PWDF_USB_INTERFACE_SELECT_SETTING_PARAMS inParams)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceAllocAndQueryString(', 'WDFUSBDEVICE inUsbDevice, PWDF_OBJECT_ATTRIBUTES inStringMemoryAttributes, outWDFMEMORY* StringMemory, PUSHORT outNumCharacters, UCHAR inStringIndex, USHORT inLangID)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceCreate(', 'WDFDEVICE inDevice, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFUSBDEVICE* UsbDevice)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceCyclePortSynchronously(', 'WDFUSBDEVICE inUsbDevice)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceFormatRequestForControlTransfer(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, PWDF_USB_CONTROL_SETUP_PACKET inSetupPacket, WDFMEMORY inTransferMemory, PWDFMEMORY_OFFSET inTransferOffset)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceFormatRequestForCyclePort(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceFormatRequestForString(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, WDFMEMORY inMemory, PWDFMEMORY_OFFSET inOffset, UCHAR inStringIndex, USHORT inLangID)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceFormatRequestForUrb(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, WDFMEMORY inUrbMemory, PWDFMEMORY_OFFSET inUrbMemoryOffset)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceGetDeviceDescriptor(', 'WDFUSBDEVICE inUsbDevice, PUSB_DEVICE_DESCRIPTOR outUsbDeviceDescriptor)', 'VOID', '')
call cppapi#function('WdfUsbTargetDeviceGetInterface(', 'WDFUSBDEVICE inUsbDevice, UCHAR inInterfaceIndex)', 'WDFUSBINTERFACE', '')
call cppapi#function('WdfUsbTargetDeviceGetNumInterfaces(', 'WDFUSBDEVICE inUsbDevice)', 'UCHAR', '')
call cppapi#function('WdfUsbTargetDeviceIsConnectedSynchronous(', 'WDFUSBDEVICE inUsbDevice)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceQueryString(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PUSHORT String, PUSHORT ioNumCharacters, UCHAR inStringIndex, USHORT inLangID)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceResetPortSynchronously(', 'WDFUSBDEVICE inUsbDevice)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceRetrieveConfigDescriptor(', 'WDFUSBDEVICE inUsbDevice, PVOID ConfigDescriptor, PUSHORT ioConfigDescriptorLength)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceRetrieveCurrentFrameNumber(', 'WDFUSBDEVICE inUsbDevice, PULONG outCurrentFrameNumber)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceRetrieveInformation(', 'WDFUSBDEVICE inUsbDevice, PWDF_USB_DEVICE_INFORMATION outInformation)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceSelectConfig(', 'WDFUSBDEVICE inUsbDevice, PWDF_OBJECT_ATTRIBUTES inPipeAttributes, PWDF_USB_DEVICE_SELECT_CONFIG_PARAMS ioParams)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceSendControlTransferSynchronously(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PWDF_USB_CONTROL_SETUP_PACKET inSetupPacket, PWDF_MEMORY_DESCRIPTOR inMemoryDescriptor, PULONG outBytesTransferred)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceSendUrbSynchronously(', 'WDFUSBDEVICE inUsbDevice, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PURB Urb)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetDeviceWdmGetConfigurationHandle(', 'WDFUSBDEVICE inUsbDevice)', 'USBD_CONFIGURATION_HANDLE', '')
call cppapi#function('WdfUsbTargetPipeAbortSynchronously(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeConfigContinuousReader(', 'WDFUSBPIPE inPipe, PWDF_USB_CONTINUOUS_READER_CONFIG inConfig)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeFormatRequestForAbort(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeFormatRequestForRead(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, WDFMEMORY inReadMemory, PWDFMEMORY_OFFSET inReadOffset)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeFormatRequestForReset(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeFormatRequestForUrb(', 'WDFUSBPIPE inPIPE, WDFREQUEST inRequest, WDFMEMORY inUrbMemory, PWDFMEMORY_OFFSET inUrbMemoryOffset)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeFormatRequestForWrite(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, WDFMEMORY inWriteMemory, PWDFMEMORY_OFFSET inWriteOffset)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeGetInformation(', 'WDFUSBPIPE inPipe, PWDF_USB_PIPE_INFORMATION outPipeInformation)', 'VOID', '')
call cppapi#function('WdfUsbTargetPipeGetType(', 'WDFUSBPIPE inPipe)', 'WDF_USB_PIPE_TYPE', '')
call cppapi#function('WdfUsbTargetPipeIsInEndpoint(', 'WDFUSBPIPE inPipe)', 'BOOLEAN', '')
call cppapi#function('WdfUsbTargetPipeIsOutEndpoint(', 'WDFUSBPIPE inPipe)', 'BOOLEAN', '')
call cppapi#function('WdfUsbTargetPipeReadSynchronously(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PWDF_MEMORY_DESCRIPTOR inMemoryDescriptor, PULONG outBytesRead)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeResetSynchronously(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeSendUrbSynchronously(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PURB Urb)', 'NTSTATUS', '')
call cppapi#function('WdfUsbTargetPipeSetNoMaximumPacketSizeCheck(', 'WDFUSBPIPE inPipe)', 'VOID', '')
call cppapi#function('WdfUsbTargetPipeWdmGetPipeHandle(', 'WDFUSBPIPE inUsbPipe)', 'USBD_PIPE_HANDLE', '')
call cppapi#function('WdfUsbTargetPipeWriteSynchronously(', 'WDFUSBPIPE inPipe, WDFREQUEST inRequest, PWDF_REQUEST_SENDIONS inRequestOptions, PWDF_MEMORY_DESCRIPTOR inMemoryDescriptor, PULONG outBytesWritten)', 'NTSTATUS', '')
call cppapi#function('WdfWaitLockAcquire(', 'WDFWAITLOCK inLock, PLONGLONG inTimeout)', 'NTSTATUS', '')
call cppapi#function('WdfWaitLockCreate(', 'PWDF_OBJECT_ATTRIBUTES inLockAttributes, outWDFWAITLOCK* Lock)', 'NTSTATUS', '')
call cppapi#function('WdfWaitLockRelease(', 'WDFWAITLOCK inLock)', 'VOID', '')
call cppapi#function('WdfWdmDeviceGetWdfDeviceHandle(', 'PDEVICE_OBJECT inDeviceObject)', 'WDFDEVICE', '')
call cppapi#function('WdfWdmDriverGetWdfDriverHandle(', 'PDRIVER_OBJECT inDriverObject)', 'WDFDRIVER', '')
call cppapi#function('WdfWmiInstanceCreate(', 'WDFDEVICE inDevice, PWDF_WMI_INSTANCE_CONFIG inInstanceConfig, PWDF_OBJECT_ATTRIBUTES inInstanceAttributes, outWDFWMIINSTANCE* Instance)', 'NTSTATUS', '')
call cppapi#function('WdfWmiInstanceDeregister(', 'WDFWMIINSTANCE inWmiInstance)', 'VOID', '')
call cppapi#function('WdfWmiInstanceFireEvent(', 'WDFWMIINSTANCE inWmiInstance, ULONG inEventDataSize, PVOID EventData)', 'NTSTATUS', '')
call cppapi#function('WdfWmiInstanceGetDevice(', 'WDFWMIINSTANCE inWmiInstance)', 'WDFDEVICE', '')
call cppapi#function('WdfWmiInstanceGetProvider(', 'WDFWMIINSTANCE inWmiInstance)', 'WDFWMIPROVIDER', '')
call cppapi#function('WdfWmiInstanceRegister(', 'WDFWMIINSTANCE inWmiInstance)', 'NTSTATUS', '')
call cppapi#function('WdfWmiProviderCreate(', 'WDFDEVICE inDevice, PWDF_WMI_PROVIDER_CONFIG inWmiProviderConfig, PWDF_OBJECT_ATTRIBUTES inProviderAttributes, outWDFWMIPROVIDER* WmiProvider)', 'NTSTATUS', '')
call cppapi#function('WdfWmiProviderGetDevice(', 'WDFWMIPROVIDER inWmiProvider)', 'WDFDEVICE', '')
call cppapi#function('WdfWmiProviderGetTracingHandle(', 'WDFWMIPROVIDER inWmiProvider)', 'ULONGLONG', '')
call cppapi#function('WdfWmiProviderIsEnabled(', 'WDFWMIPROVIDER inWmiProvider, WDF_WMI_PROVIDER_CONTROL inProviderControl)', 'BOOLEAN', '')
call cppapi#function('WdfWorkItemCreate(', 'PWDF_WORKITEM_CONFIG inConfig, PWDF_OBJECT_ATTRIBUTES inAttributes, outWDFWORKITEM* WorkItem)', 'NTSTATUS', '')
call cppapi#function('WdfWorkItemEnqueue(', 'WDFWORKITEM inWorkItem)', 'VOID', '')
call cppapi#function('WdfWorkItemFlush(', 'WDFWORKITEM inWorkItem)', 'VOID', '')
call cppapi#function('WdfWorkItemGetParentObject(', 'WDFWORKITEM inWorkItem)', 'WDFOBJECT', '')
